" Basics {{{
let mapleader = "\<Space>"
language en_US.UTF-8                                                           " set the current language
filetype plugin indent on                                                      " add filetype, plugin, and indent support
syntax on                                                                      " turn on syntax highlighting
if !exists('g:loaded_matchit') && findfile('plugin/matchit.vim', &rtp) ==# ''
  runtime! macros/matchit.vim                                                  " `matchit.vim` is built-in so let's enable it! (hit `%` on `if` to jump to `else`)
endif

" Cursor settings
" 0, 1 or none    blinking block cursor
" 2               block cursor
" 3               blinking underline cursor
" 4               underline cursor
" 5               blinking vertical bar cursor
" 6               vertical bar cursor
let &t_ti.="\e[1 q"                                                            " put terminal into 'termcap' mode
let &t_te.="\e[1 q"                                                            " end of 'termcap' mode
let &t_SI.="\e[5 q"                                                            " start insert mode (blinking vertical bar cursor)
let &t_SR.="\e[4 q"                                                            " start replace mode (underline cursor)
let &t_EI.="\e[1 q"                                                            " end insert or replace mode (blinking block cursor)
" }}}

" Settings {{{
set nocompatible                                                               " don't behave very Vi compatible
set pastetoggle=<F2>                                                           " key sequence to toggle paste mode
set nostartofline                                                              " many jump commands move the cursor to the first non-blank character of a line
set path=.,**                                                                  " relative to current file and everything under :pwd
set incsearch                                                                  " show match for partly typed search command
set ignorecase                                                                 " ignore case when using a search pattern
set smartcase                                                                  " override 'ignorecase' when pattern has upper case characters
set scrolloff=8                                                                " number of screen lines to show around the cursor
set nowrap                                                                     " don't long lines wrap
set lazyredraw                                                                 " don't redraw while executing macros
set list                                                                       " show <Tab> as ^I and end-of-line as $
set listchars=tab:»·,trail:·,nbsp:·                                            " list of strings used for list mode
set number                                                                     " show the line number for each line
set relativenumber                                                             " show the relative line number for each line
set hlsearch                                                                   " highlight all matches for the last used search pattern
if has('termguicolors')
  set termguicolors                                                            " use GUI colors for the terminal
endif
set cursorline                                                                 " highlight the screen line of the cursor
if has('syntax')
  set spelllang=en_us                                                          " list of accepted languages
  let spelldir = $HOME . '/.vim/spell'
  if !isdirectory(spelldir) | call mkdir(spelldir, 'p') | endif
  let &spellfile=spelldir . '/en.utf-8.add'                                    " file that 'zg' adds good words to
endif
set hidden                                                                     " don't unload a buffer when no longer shown in a window
set splitbelow                                                                 " a new window is put below the current one
set splitright                                                                 " a new window is put right of the current one
set ttyfast                                                                    " terminal connection is fast
set title                                                                      " show info in the window title
set titlestring=%(%F%)%a\ -\ VIM%(\ %M%)                                       " when not empty, string to be used for the window title
set ruler                                                                      " show cursor position below each window
set confirm                                                                    " start a dialog when a command fails
set visualbell                                                                 " use a visual bell instead of beeping
if has('persistent_undo')
  set undofile                                                                 " automatically save and restore undo history
  let &undodir = $HOME . '/.vim/undodir'                                       " list of directories for undo files
  if !isdirectory(&undodir) | call mkdir(&undodir, 'p') | endif
endif
set backspace=indent,eol,start                                                 " specifies what <BS>, CTRL-W, etc. can do in Insert mode
if has('patch-7.3.541')
  set formatoptions+=j                                                         " list of flags that tell how automatic formatting works
endif
set complete+=kspell                                                           " specifies how Insert mode completion works for CTRL-N and CTRL-P
set completeopt=menuone,preview                                                " whether to use a popup menu for Insert mode completion
set showmatch                                                                  " when inserting a bracket, briefly jump to its match
set nojoinspaces                                                               " use two spaces after '.' when joining a line
set tabstop=4                                                                  " number of spaces a <Tab> in the text stands for
set shiftwidth=4                                                               " number of spaces used for each step of (auto)indent
set smarttab                                                                   " a <Tab> in an indent inserts 'shiftwidth' spaces
set softtabstop=4                                                              " if non-zero, number of spaces to insert for a <Tab>
set expandtab                                                                  " expand <Tab> to spaces in Insert mode
set autoindent                                                                 " automatically set the indent of a new line
set smartindent                                                                " do clever autoindenting
set nofoldenable                                                               " display all folds open
set diffopt+=vertical                                                          " options for using diff mode
set ttimeoutlen=0                                                              " the time in milliseconds that is waited for a key code or mapped key sequence to complete
set nobackup                                                                   " don't keep a backup after overwriting a file
set autowrite                                                                  " automatically write a file when leaving a modified buffer
set autoread                                                                   " don't automatically read a file when it was modified outside of Vim
set noswapfile                                                                 " use a swap file for this buffer
set history=1000                                                               " how many command lines are remembered
set wildmode=longest:full,full                                                 " when more than one match, list all matches and complete till longest common string
set wildignore=.git/*,.idea/*                                                  " list of patterns to ignore files for file name completion
set wildignorecase                                                             " ignore case when completing file names
set wildmenu                                                                   " command-line completion shows a list of matches
set grepformat=%f:%l:%c:%m,%f:%l:%m,%f:%l%m,%f\ \ %l%m                         " list of formats for output of 'grepprg'
if executable('rg')
  set grepprg=rg\ --no-heading\ --vimgrep                                      " program used for the ":grep" command
endif
set encoding=utf-8                                                             " character encoding used in Vim
" }}}

" Plugins {{{
" install vim-plug if it's not already
augroup vimPlug
  autocmd!
  if empty(glob('~/.vim/autoload/plug.vim'))
    silent! curl -fLo ~/.vim/autoload/plug.vim --create-dirs
          \ https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
    autocmd VimEnter * PlugInstall --sync | source $MYVIMRC
  endif
augroup END

call plug#begin('~/.vim/plugged')

" darcula theme {{{
Plug 'doums/darcula'                                                           " a vim color scheme reproduction of the official JetBrains IDE Darcula theme
" }}}

" vim-surround {{{
Plug 'tpope/vim-surround'                                                      " easily delete, change and add such surroundings in pairs
" }}}

" vim-repeat {{{
Plug 'tpope/vim-repeat'                                                        " enable repeating supported plugin maps with '.'
" }}}

" vim-commentray {{{
Plug 'tpope/vim-commentary'                                                    " comment stuff out
" }}}

" vim-fugitive {{{
Plug 'tpope/vim-fugitive'                                                      " a git wrapper
" }}}

" vim-speeddating {{{
Plug 'tpope/vim-speeddating'                                                   " use CTRL-A/CTRL-X to increment dates, times, and more
" }}}

" snippets {{{
Plug 'SirVer/ultisnips'                                                        " the ultimate solution for snippets in vim
let g:UltiSnipsExpandTrigger = '<tab>'
let g:UltiSnipsJumpForwardTrigger = '<tab>'
let g:UltiSnipsJumpBackwardTrigger = '<s-tab>'

Plug 'honza/vim-snippets'                                                      " snippets files for various programming languages
" }}}

" supertab {{{
Plug 'ervandew/supertab'                                                       " perform all your vim insert mode completions with Tab
let g:SuperTabDefaultCompletionType = '<C-n>'
let g:SuperTabCrMapping = 0
" }}}

" nerdtree {{{
Plug 'preservim/nerdtree'                                                      " a tree explorer plugin for vim
" }}}

" markdown {{{
Plug 'godlygeek/tabular'                                                       " vim script for text filtering and alignment
Plug 'plasticboy/vim-markdown'                                                 " markdown vim mode
let g:vim_markdown_folding_disabled = 1
" }}}

" goyo.vim {{{
Plug 'junegunn/goyo.vim'                                                       " distraction-free writing in vim
" }}}

" vim-table-mode {{{
Plug 'dhruvasagar/vim-table-mode'                                              " vim table mode for instant table creation
" }}}

" fzf {{{
Plug '/usr/local/opt/fzf'                                                      " fzf
Plug 'junegunn/fzf.vim'                                                        " basic wrapper function for vim
nnoremap <leader>ff :Files<CR>
nnoremap <leader>fb :Buffers<CR>
" }}}

" floaterm.vim {{{
Plug 'voldikss/vim-floaterm'                                                   " terminal manager for (neo)vim
nnoremap <silent> <F12> :FloatermToggle<CR>
tnoremap <silent> <F12> <C-\><C-n>:FloatermToggle<CR>
" }}}

" textobjs {{{
Plug 'kana/vim-textobj-user'                                                  " create your own text objects
Plug 'kana/vim-textobj-entire'                                                " text objects for entire buffer
Plug 'kana/vim-textobj-line'                                                  " text objects for the current line
Plug 'beloglazov/vim-textobj-quotes'                                          " text objects for quoted characters
Plug 'kana/vim-textobj-function'                                              " text objects for functions
Plug 'sgur/vim-textobj-parameter'                                             " text objects for parameters
Plug 'glts/vim-textobj-comment'                                               " text objects for comments
" }}}
call plug#end()
" }}}

" Color-Scheme {{{
colorscheme darcula                                                            " load color scheme
" }}}

" Mappings {{{
" command-line hjkl-style search
cnoremap <C-k> <Up>
cnoremap <C-j> <Down>
" prefer to use <C-A> to the first character of the line
cnoremap <C-A> <Home>

" prefer to use (Shift) + Enter to insert line
nnoremap <CR> o<Esc>
nnoremap <S-Enter> O<Esc>
inoremap <S-Enter> <C-o>O

" disable <Up>/<Down>/<Left>/<Right>
nnoremap <Up> <NOP>
nnoremap <Down> <NOP>
nnoremap <Left> <NOP>
nnoremap <Right> <NOP>
inoremap <Up> <NOP>
inoremap <Down> <NOP>
inoremap <Left> <NOP>
inoremap <Right> <NOP>
vnoremap <Up> <NOP>
vnoremap <Down> <NOP>
vnoremap <Left> <NOP>
vnoremap <Right> <NOP>

" prefer to use Y to yank characters from the cursor position to the end of the line
nnoremap Y y$

" buffer navigation
noremap <leader>1 :bfirst<CR>
noremap [B :bfirst<CR>
noremap <leader>9 :blast<CR>
noremap ]B :blast<CR>
noremap <leader>h :bprevious<CR>
noremap [b :bprevious<CR>
noremap <leader>l :bnext<CR>
noremap ]b :bnext<CR>
" open the last buffer
nnoremap <leader><leader> <C-^>
" show all open buffers and their status
nnoremap <leader>bb :buffers<CR>
" open a new empty buffer
nnoremap <leader>bn :enew<CR>
" close the current buffer, moves to the previous one
nnoremap <leader>bd :bdelete<CR>
" forces buffer close
nnoremap <leader>bD :bdelete!<CR>

" window navigation
nnoremap <C-h> <C-w>h
nnoremap <C-j> <C-w>j
nnoremap <C-k> <C-w>k
nnoremap <C-l> <C-w>l

" tab navigation
nnoremap [t :tabprevious<CR>
nnoremap ]t :tabnext<CR>
nnoremap [T :tabfirst<CR>
nnoremap ]T :tablast<CR>

" quickfix list navigation
nnoremap [q :cprevious<CR>
nnoremap ]q :cnext<CR>
nnoremap [Q :cfirst<CR>
nnoremap ]Q :clast<CR>

" location list navigation
nnoremap [l :lprevious<CR>
nnoremap ]l :lnext<CR>
nnoremap [L :lfirst<CR>
nnoremap ]L :llast<CR>

" move lines with Alt + J/K
if has('mac') && !exists('+macmeta')
  nnoremap ∆ :m +1<CR>
  nnoremap ˚ :m -2<CR>
  vnoremap ∆ :m '>+1<CR>gvgv
  vnoremap ˚ :m '<-2<CR>gvgv
endif

" toggle word wrap
nnoremap <leader>wl :set wrap! linebreak!<CR>
" toggle spell checking
nnoremap <leader>sp :set spell!<CR>
nnoremap <leader>ms :mkspell! <C-r>=&spellfile<CR><CR>
" remove search highlighting
nnoremap <C-/> :nohlsearch<CR><C-l>

" make ascii art font
nnoremap <leader>aF :.!toilet -w 200 -f standard<CR>
nnoremap <leader>af :.!toilet -w 200 -f small<CR>
" make ascii border
nnoremap <leader>ab :.!toilet -w 200 -f term -F border<CR>

" system clipboard
vnoremap <leader>y "+y
vnoremap <leader>d "+d
nnoremap <leader>y "+yy
nnoremap <leader>p "+p
nnoremap <leader>P "+P
vnoremap <leader>p "+p
vnoremap <leader>P "+P

" save file
nnoremap <C-s> :update<CR>

" quit vim
nnoremap <C-q> :quit<CR>

" execute command
nnoremap <leader><Enter> !!zsh<CR>

" automatically disable paste mode when leaving insert mode
autocmd InsertLeave * set nopaste
" }}}

" abbreviations {{{
cabbrev vf vertical find
" }}}
